version: "3.9"

services:
  next:
    build: client/
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
  chat:
    build: chat/
    restart: always
    ports:
      - "4000:4000"
    
